// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestRemakeServer;

namespace TestRemakeServer.Migrations
{
    [DbContext(typeof(ClockProilesContext))]
    partial class ClockProilesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("TestRemakeServer.DbModels.ClockProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FaceColor");

                    b.Property<string>("HandsColor");

                    b.Property<string>("Name");

                    b.Property<string>("Timezone");

                    b.HasKey("ID");

                    b.ToTable("ClockProiles");
                });
#pragma warning restore 612, 618
        }
    }
}
